// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Security {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghTZWN1cml0eSr1AgoLQ2lwaGVyU3VpdGUSCwoHQUVT",
            "X0VDQhAAEgsKB0FFU19DQkMQARILCgdBRVNfQ0ZCEAISCwoHQUVTX09GQhAD",
            "EgsKB0FFU19DVFIQBBIMCghBUklBX0VDQhAFEgwKCEFSSUFfQ0JDEAYSDAoI",
            "QVJJQV9DRkIQBxIMCghBUklBX09GQhAIEgwKCEFSSUFfQ1RSEAkSDQoJSElH",
            "SFRfRUNCEAoSDQoJSElHSFRfQ0JDEAsSDQoJSElHSFRfQ0ZCEAwSDQoJSElH",
            "SFRfT0ZCEA0SDQoJSElHSFRfQ1RSEA4SDQoJU1BFQ0tfRUNCEA8SDQoJU1BF",
            "Q0tfQ0JDEBASDQoJU1BFQ0tfQ0ZCEBESDQoJU1BFQ0tfT0ZCEBISDQoJU1BF",
            "Q0tfQ1RSEBMSDQoJVFdJTkVfRUNCEBQSDQoJVFdJTkVfQ0JDEBUSDQoJVFdJ",
            "TkVfQ0ZCEBYSDQoJVFdJTkVfT0ZCEBcSDQoJVFdJTkVfQ1RSEBgqXQoFTXNn",
            "SWQSCwoHQ19IRUxMTxAAEgsKB1NfSEVMTE8QARIQCgxDX0hFTExPX0RPTkUQ",
            "AhIQCgxTX0hFTExPX0RPTkUQAxIKCgZDX1RFU1QQBBIKCgZTX1RFU1QQBUIb",
            "qgIYR29vZ2xlLlByb3RvYnVmLlNlY3VyaXR5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Security.CipherSuite), typeof(global::Google.Protobuf.Security.MsgId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CipherSuite {
    [pbr::OriginalName("AES_ECB")] AesEcb = 0,
    [pbr::OriginalName("AES_CBC")] AesCbc = 1,
    [pbr::OriginalName("AES_CFB")] AesCfb = 2,
    [pbr::OriginalName("AES_OFB")] AesOfb = 3,
    [pbr::OriginalName("AES_CTR")] AesCtr = 4,
    [pbr::OriginalName("ARIA_ECB")] AriaEcb = 5,
    [pbr::OriginalName("ARIA_CBC")] AriaCbc = 6,
    [pbr::OriginalName("ARIA_CFB")] AriaCfb = 7,
    [pbr::OriginalName("ARIA_OFB")] AriaOfb = 8,
    [pbr::OriginalName("ARIA_CTR")] AriaCtr = 9,
    [pbr::OriginalName("HIGHT_ECB")] HightEcb = 10,
    [pbr::OriginalName("HIGHT_CBC")] HightCbc = 11,
    [pbr::OriginalName("HIGHT_CFB")] HightCfb = 12,
    [pbr::OriginalName("HIGHT_OFB")] HightOfb = 13,
    [pbr::OriginalName("HIGHT_CTR")] HightCtr = 14,
    [pbr::OriginalName("SPECK_ECB")] SpeckEcb = 15,
    [pbr::OriginalName("SPECK_CBC")] SpeckCbc = 16,
    [pbr::OriginalName("SPECK_CFB")] SpeckCfb = 17,
    [pbr::OriginalName("SPECK_OFB")] SpeckOfb = 18,
    [pbr::OriginalName("SPECK_CTR")] SpeckCtr = 19,
    [pbr::OriginalName("TWINE_ECB")] TwineEcb = 20,
    [pbr::OriginalName("TWINE_CBC")] TwineCbc = 21,
    [pbr::OriginalName("TWINE_CFB")] TwineCfb = 22,
    [pbr::OriginalName("TWINE_OFB")] TwineOfb = 23,
    [pbr::OriginalName("TWINE_CTR")] TwineCtr = 24,
  }

  public enum MsgId {
    [pbr::OriginalName("C_HELLO")] CHello = 0,
    [pbr::OriginalName("S_HELLO")] SHello = 1,
    [pbr::OriginalName("C_HELLO_DONE")] CHelloDone = 2,
    [pbr::OriginalName("S_HELLO_DONE")] SHelloDone = 3,
    [pbr::OriginalName("C_TEST")] CTest = 4,
    [pbr::OriginalName("S_TEST")] STest = 5,
  }

  #endregion

}

#endregion Designer generated code
