// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum_Security.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Security {

  /// <summary>Holder for reflection information generated from Enum_Security.proto</summary>
  public static partial class EnumSecurityReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum_Security.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumSecurityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNFbnVtX1NlY3VyaXR5LnByb3RvEghTZWN1cml0eSr9AwoFTXNnSWQSCwoH",
            "Q19IRUxMTxAAEgsKB1NfSEVMTE8QARIQCgxDX0hFTExPX0RPTkUQAhIQCgxT",
            "X0hFTExPX0RPTkUQAxIOCgpDX1JFR0lTVEVSEAQSDgoKU19SRUdJU1RFUhAF",
            "EgsKB0NfTE9HSU4QBhILCgdTX0xPR0lOEAcSDwoLQ19FTlRFUlJPT00QCBIP",
            "CgtTX0VOVEVSUk9PTRAJEg4KCkNfRU5URVJNQVAQChIOCgpTX0VOVEVSTUFQ",
            "EAsSFwoTU19FTlRFUk1BUEJST0FEQ0FTVBAMEg8KC0NfTEVBVkVST09NEA0S",
            "DwoLU19MRUFWRVJPT00QDhIOCgpDX0xFQVZFTUFQEA8SDgoKU19MRUFWRU1B",
            "UBAQEgoKBkNfQ0hBVBAREgoKBlNfQ0hBVBASEg8KC0NfTU9WRVNUQVJUEBMS",
            "DwoLU19NT1ZFU1RBUlQQFBIMCghDX01PVklORxAVEgwKCFNfTU9WSU5HEBYS",
            "DQoJQ19NT1ZFRU5EEBcSDQoJU19NT1ZFRU5EEBgSCgoGQ19KVU1QEBkSCgoG",
            "U19KVU1QEBoSCgoGQ19GQUxMEBsSCgoGU19GQUxMEBwSCgoGQ19MQU5EEB0S",
            "CgoGU19MQU5EEB4SCwoHQ19TS0lMTBAfEgsKB1NfU0tJTEwQIBIJCgVTX0hJ",
            "VBAhKvUCCgtDaXBoZXJTdWl0ZRILCgdBRVNfRUNCEAASCwoHQUVTX0NCQxAB",
            "EgsKB0FFU19DRkIQAhILCgdBRVNfT0ZCEAMSCwoHQUVTX0NUUhAEEgwKCEFS",
            "SUFfRUNCEAUSDAoIQVJJQV9DQkMQBhIMCghBUklBX0NGQhAHEgwKCEFSSUFf",
            "T0ZCEAgSDAoIQVJJQV9DVFIQCRINCglISUdIVF9FQ0IQChINCglISUdIVF9D",
            "QkMQCxINCglISUdIVF9DRkIQDBINCglISUdIVF9PRkIQDRINCglISUdIVF9D",
            "VFIQDhINCglTUEVDS19FQ0IQDxINCglTUEVDS19DQkMQEBINCglTUEVDS19D",
            "RkIQERINCglTUEVDS19PRkIQEhINCglTUEVDS19DVFIQExINCglUV0lORV9F",
            "Q0IQFBINCglUV0lORV9DQkMQFRINCglUV0lORV9DRkIQFhINCglUV0lORV9P",
            "RkIQFxINCglUV0lORV9DVFIQGCowCgdNb3ZlRGlyEggKBExFRlQQABIJCgVS",
            "SUdIVBABEgYKAlVQEAISCAoERE9XThADKkYKBVN0YXRlEggKBElETEUQABIK",
            "CgZNT1ZJTkcQARIICgRKVU1QEAISCAoERkFMTBADEggKBExBTkQQBBIJCgVT",
            "S0lMTBAFQhuqAhhHb29nbGUuUHJvdG9idWYuU2VjdXJpdHliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Security.MsgId), typeof(global::Google.Protobuf.Security.CipherSuite), typeof(global::Google.Protobuf.Security.MoveDir), typeof(global::Google.Protobuf.Security.State), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgId {
    [pbr::OriginalName("C_HELLO")] CHello = 0,
    [pbr::OriginalName("S_HELLO")] SHello = 1,
    [pbr::OriginalName("C_HELLO_DONE")] CHelloDone = 2,
    [pbr::OriginalName("S_HELLO_DONE")] SHelloDone = 3,
    [pbr::OriginalName("C_REGISTER")] CRegister = 4,
    [pbr::OriginalName("S_REGISTER")] SRegister = 5,
    [pbr::OriginalName("C_LOGIN")] CLogin = 6,
    [pbr::OriginalName("S_LOGIN")] SLogin = 7,
    [pbr::OriginalName("C_ENTERROOM")] CEnterroom = 8,
    [pbr::OriginalName("S_ENTERROOM")] SEnterroom = 9,
    [pbr::OriginalName("C_ENTERMAP")] CEntermap = 10,
    [pbr::OriginalName("S_ENTERMAP")] SEntermap = 11,
    [pbr::OriginalName("S_ENTERMAPBROADCAST")] SEntermapbroadcast = 12,
    [pbr::OriginalName("C_LEAVEROOM")] CLeaveroom = 13,
    [pbr::OriginalName("S_LEAVEROOM")] SLeaveroom = 14,
    [pbr::OriginalName("C_LEAVEMAP")] CLeavemap = 15,
    [pbr::OriginalName("S_LEAVEMAP")] SLeavemap = 16,
    [pbr::OriginalName("C_CHAT")] CChat = 17,
    [pbr::OriginalName("S_CHAT")] SChat = 18,
    [pbr::OriginalName("C_MOVESTART")] CMovestart = 19,
    [pbr::OriginalName("S_MOVESTART")] SMovestart = 20,
    [pbr::OriginalName("C_MOVING")] CMoving = 21,
    [pbr::OriginalName("S_MOVING")] SMoving = 22,
    [pbr::OriginalName("C_MOVEEND")] CMoveend = 23,
    [pbr::OriginalName("S_MOVEEND")] SMoveend = 24,
    [pbr::OriginalName("C_JUMP")] CJump = 25,
    [pbr::OriginalName("S_JUMP")] SJump = 26,
    [pbr::OriginalName("C_FALL")] CFall = 27,
    [pbr::OriginalName("S_FALL")] SFall = 28,
    [pbr::OriginalName("C_LAND")] CLand = 29,
    [pbr::OriginalName("S_LAND")] SLand = 30,
    [pbr::OriginalName("C_SKILL")] CSkill = 31,
    [pbr::OriginalName("S_SKILL")] SSkill = 32,
    [pbr::OriginalName("S_HIT")] SHit = 33,
  }

  public enum CipherSuite {
    [pbr::OriginalName("AES_ECB")] AesEcb = 0,
    [pbr::OriginalName("AES_CBC")] AesCbc = 1,
    [pbr::OriginalName("AES_CFB")] AesCfb = 2,
    [pbr::OriginalName("AES_OFB")] AesOfb = 3,
    [pbr::OriginalName("AES_CTR")] AesCtr = 4,
    [pbr::OriginalName("ARIA_ECB")] AriaEcb = 5,
    [pbr::OriginalName("ARIA_CBC")] AriaCbc = 6,
    [pbr::OriginalName("ARIA_CFB")] AriaCfb = 7,
    [pbr::OriginalName("ARIA_OFB")] AriaOfb = 8,
    [pbr::OriginalName("ARIA_CTR")] AriaCtr = 9,
    [pbr::OriginalName("HIGHT_ECB")] HightEcb = 10,
    [pbr::OriginalName("HIGHT_CBC")] HightCbc = 11,
    [pbr::OriginalName("HIGHT_CFB")] HightCfb = 12,
    [pbr::OriginalName("HIGHT_OFB")] HightOfb = 13,
    [pbr::OriginalName("HIGHT_CTR")] HightCtr = 14,
    [pbr::OriginalName("SPECK_ECB")] SpeckEcb = 15,
    [pbr::OriginalName("SPECK_CBC")] SpeckCbc = 16,
    [pbr::OriginalName("SPECK_CFB")] SpeckCfb = 17,
    [pbr::OriginalName("SPECK_OFB")] SpeckOfb = 18,
    [pbr::OriginalName("SPECK_CTR")] SpeckCtr = 19,
    [pbr::OriginalName("TWINE_ECB")] TwineEcb = 20,
    [pbr::OriginalName("TWINE_CBC")] TwineCbc = 21,
    [pbr::OriginalName("TWINE_CFB")] TwineCfb = 22,
    [pbr::OriginalName("TWINE_OFB")] TwineOfb = 23,
    [pbr::OriginalName("TWINE_CTR")] TwineCtr = 24,
  }

  public enum MoveDir {
    [pbr::OriginalName("LEFT")] Left = 0,
    [pbr::OriginalName("RIGHT")] Right = 1,
    [pbr::OriginalName("UP")] Up = 2,
    [pbr::OriginalName("DOWN")] Down = 3,
  }

  public enum State {
    [pbr::OriginalName("IDLE")] Idle = 0,
    [pbr::OriginalName("MOVING")] Moving = 1,
    [pbr::OriginalName("JUMP")] Jump = 2,
    [pbr::OriginalName("FALL")] Fall = 3,
    [pbr::OriginalName("LAND")] Land = 4,
    [pbr::OriginalName("SKILL")] Skill = 5,
  }

  #endregion

}

#endregion Designer generated code
